=== Brest-Java-Course/Alexander-Kruglikov/BankDepositHibernate/app-client-soap/src/main/resources/deposits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <xsd:complexType name="bankDepositor_type">
        <xsd:sequence>
            <xsd:element name="depositorId" type="xsd:long"/>
            <xsd:element name="depositorName">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[A-Z][a-z]+[0-9]*"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="depositorDateDeposit" type="xsd:date"/>
            <xsd:element name="depositorAmountDeposit">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                        <xsd:minInclusive value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="depositorAmountPlusDeposit">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="depositorAmountMinusDeposit">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="depositorDateReturnDeposit" type="xsd:date"/>
            <xsd:element name="depositorMarkReturnDeposit">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:pattern value="[0,1]"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="bankDepositors_type">
        <xsd:sequence>
            <xsd:element name="bankDepositor" type="bankDepositor_type" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="bankDeposit_type">
        <xsd:sequence>
            <xsd:element name="depositId" type="xsd:long" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="depositName">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[A-Z][a-z]+[0-9]*"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="depositMinTerm">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                        <xsd:minExclusive value="1"/>
                        <xsd:maxInclusive value="480"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="depositMinAmount">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                        <xsd:minInclusive value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="depositCurrency">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[A-Z]{3}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="depositInterestRate">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                        <xsd:minInclusive value="1"/>
                        <xsd:maxInclusive value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="depositAddConditions" type="xsd:string" minOccurs="0"/>
            <xsd:element name="bankDepositors" type="bankDepositors_type" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="bankDeposits_type">
        <xsd:sequence>
            <xsd:element name="bankDeposit" type="bankDeposit_type" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="bankDeposits" type="bankDeposits_type"/>

</xsd:schema>

=== Brest-Java-Course/Alexander-Kruglikov/BankDepositHibernate/app-client-soap/src/main/resources/depositsExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='deposits.xsl'?>
<bankDeposits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="deposits.xsd">
    <bankDeposit>
        <depositId>1</depositId>
        <depositName>Name1</depositName>
        <depositMinTerm>12</depositMinTerm>
        <depositMinAmount>100</depositMinAmount>
        <depositCurrency>USD</depositCurrency>
        <depositInterestRate>100</depositInterestRate>
        <depositAddConditions>Conditions</depositAddConditions>
        <bankDepositors>
            <bankDepositor>
                <depositorId>1</depositorId>
                <depositorName>Name11</depositorName>
                <depositorDateDeposit>2015-01-01</depositorDateDeposit>
                <depositorAmountDeposit>1000</depositorAmountDeposit>
                <depositorAmountPlusDeposit>10</depositorAmountPlusDeposit>
                <depositorAmountMinusDeposit>10</depositorAmountMinusDeposit>
                <depositorDateReturnDeposit>2016-01-01</depositorDateReturnDeposit>
                <depositorMarkReturnDeposit>0</depositorMarkReturnDeposit>
            </bankDepositor>
            <bankDepositor>
                <depositorId>2</depositorId>
                <depositorName>Name12</depositorName>
                <depositorDateDeposit>2015-02-02</depositorDateDeposit>
                <depositorAmountDeposit>100</depositorAmountDeposit>
                <depositorAmountPlusDeposit>100</depositorAmountPlusDeposit>
                <depositorAmountMinusDeposit>10</depositorAmountMinusDeposit>
                <depositorDateReturnDeposit>2016-02-02</depositorDateReturnDeposit>
                <depositorMarkReturnDeposit>1</depositorMarkReturnDeposit>
            </bankDepositor>
        </bankDepositors>
    </bankDeposit>
    <bankDeposit>
        <depositId>2</depositId>
        <depositName>Name2</depositName>
        <depositMinTerm>7</depositMinTerm>
        <depositMinAmount>1000</depositMinAmount>
        <depositCurrency>EUR</depositCurrency>
        <depositInterestRate>7</depositInterestRate>
        <depositAddConditions>Conditions</depositAddConditions>
        <bankDepositors></bankDepositors>
    </bankDeposit>
</bankDeposits>
